config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  root 'sections#index'
  
  get 'sessions/new'

  namespace :api do
    get 'members/index'
  end

  namespace :api do
    get 'books/index'
  end
  
   resources :sections
   resources :shelfs
   resources :books
   resources :members

   namespace :api do
      resources :shelfs, only: [:index]
      resources :books, only: [:index]
      resources :members, only: [:index]
   end


   
   
end

app/models/Permission.rb
class Permission < Struct.new(:member)

    def allow
        member && member.role == "admin" 
    end    
end    

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(member)
     member ||= Member.new 
      if member.role == "admin" 
        can :manage, Section
        can :manage, Shelf
        can :manage, Book
        can :manage, Member
      else
        can :read, Section
        can :read, Shelf
        can :read, Book
        can :read, Member
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :shelf
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :shelf, dependent: :destroy
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :section
  has_many :book, dependent: :destroy
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  def index
    name = params[:name]
    @books = Book.where("name LIKE ?", "%#{name}%")
    @books
  end
end

app/controllers/api/members_controller.rb
class Api::MembersController < ApplicationController
  def index
    email = params[:email]
    @members = Member.where("email LIKE ?", "%#{email}%")
    @members
  end
end

app/controllers/api/shelfs_controller.rb
class Api::ShelfsController < ApplicationController
  def index
    section_id = params[:section_id]
    render json: Shelf.where(section_id: section_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_member!
 load_and_authorize_resource

 def current_user
    current_member
 end  
 rescue_from CanCan::AccessDenied do |exception|
   redirect_to request.referrer, :alert => exception.message
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    Book.create!(book_params)
    redirect_to books_path, notice: 'Book Created Successfully'             
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def search
    @books = Book.includes(:shelf => :section).where('name LIKE ?', "%#{params[:name]}%")
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :publication_year, :shelf_id)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
  @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to root_url, notice: 'Member was successfully created.'
    else
      redirect_to root_url, notice: 'Unable to create member.'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to member_path(@member), notice: 'Member was successfully updated.'
    else
      redirect_to members_path, notice: 'Unable to update member'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to root_url, notice: ' Member was successfully destroyed And Logged Out.'

  end

  def search
    @members = Member.where('firstName LIKE ?', "%#{params[:name]}%")
  end

  private

  def member_params
    params.require(:member).permit(:firstName, :lastName, :mobileNumber, :address, :expiryDate, :role)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to section_path(@section), notice: 'Section was successfully created.'
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])

    if @section.update(section_params)
      redirect_to section_path(@section), notice: 'Section was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    redirect_to sections_path, notice: @section.name + ' Section was successfully destroyed.'
  end

  private

  def section_params
    params.require(:section).permit(:name)
  end
end

app/controllers/shelfs_controller.rb
class ShelfsController < ApplicationController
  def index
    @shelfs = Shelf.all
  end

  def show
    @shelf = Shelf.find(params[:id])
  end

  def new
    @shelf = Shelf.new
  end

  def create
    @shelf = Shelf.new(shelf_params)
    @section_id = params[:section_id]

    if @shelf.save
      redirect_to shelf_path(@shelf), notice: 'Shelf was successfully created.'
    else
      render :new
    end
  end

  def edit
    @shelf = Shelf.find(params[:id])
  end

  def update
    @shelf = Shelf.find(params[:id])

    if @shelf.update(shelf_params)
      redirect_to shelf_path(@shelf), notice: 'Shelf was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @shelf = Shelf.find(params[:id])
    @shelf.destroy

    redirect_to shelfs_path, notice: @shelf.name + ' Shelf was successfully destroyed.'
  end

  private

  def shelf_params
    params.require(:shelf).permit(:name, :section_id)
  end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/api/members_helper.rb
module Api::MembersHelper
end

app/helpers/api/shelf_helper.rb
module Api::ShelfHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/books/edit.html.erb
<div style="width: 40vw;">
<h1>Edit Book</h1>
<form class="form-horizontal" method="POST" action="<%= book_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >
  <input name="_method" value="PUT"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="book[name]" value="<%= @book.name %>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Author</label>
    <div class="col-sm-10">
     <input class="form-control" name="book[author]" value="<%= @book.author %>"/>
     </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Publication Year</label>
    <div class="col-sm-10">
     <input class="form-control" type="number" name="book[publication_year]" value="<%= @book.publication_year %>"/>
    </div>
  </div>

    <div class="form-group">
    <label class="col-sm-2 control-label">Section</label> 
    <div class="col-sm-10">
      <select class="form-control" id="sectionId">
      <option >Select Section</option>
          <% @current_section_id = Shelf.find(@book.shelf_id)[ :section_id] %>

          <% Section.all.each do |section| %>
            <option value="<%= section.id %>" <%= 'selected' if section.id == @current_section_id %>><%= section.name %></option>
          <% end %>
      </select> 
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Shelf</label> 
    <div class="col-sm-10">
      <select class="form-control" name="book[shelf_id]"  id="shelfId">
      <% Shelf.where(id: @book.shelf_id).each do |shelf| %>
      <option value="<%= shelf.id %>"><%= shelf.name %></option>
      <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Update Book</button>
      </div>
  </div>

</form>
</div>

<script>
  $(document).ready(function() {
    $('#sectionId').change(function() {
      var sectionId = $(this).val();

      $.ajax({
        url: `http://127.0.0.1:3000/api/shelfs?section_id=${sectionId}`, 
        method: 'GET',
        dataType: 'json',
        success: function(response) {
          var shelves = response;
          var shelfSelect = $('#shelfId');

          shelfSelect.empty();

          $.each(shelves, function(index, shelf) {
            shelfSelect.append($('<option></option>').val(shelf.id).text(shelf.name));
          });
        },
        error: function(xhr, status, error) {
          console.log(error);
        }
      });
    });
  });
</script>

app/views/books/index.html.erb
<div>
<h1>Books</h1>
<% if @books.empty? %>
  <p>No Books. Please add the books.</p>
<% end %>
<ol class="list-group">
  <% @books.each do |book| %>
    <li class="list-group-item list-group-item-success"><%= link_to book.name, book_path(book) %></li>
  <% end %>
</ol>
<% if can? :manage, Book %>
<%= link_to "+ Add New Book", new_book_path(), class: 'btn btn-primary btn-lg' %>
<% end %>
</div>

app/views/books/new.html.erb
<div style="width: 40vw;">
<h1>Add New Book</h1>
<form class="form-horizontal" method="POST" action="<%= books_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="book[name]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Author</label>
    <div class="col-sm-10">
     <input class="form-control" name="book[author]"/>
     </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Publication Year</label>
    <div class="col-sm-10">
     <input class="form-control" type="number" name="book[publication_year]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Section</label> 
    <div class="col-sm-10">
      <select class="form-control" id="sectionId">
      <option >Select Section</option>
          <% Section.all.each do |section| %>
            <option value="<%= section.id %>"><%= section.name %></option>
          <% end %>
      </select> 
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Shelf</label> 
    <div class="col-sm-10">
      <select class="form-control" name="book[shelf_id]"  id="shelfId">
      <option>Select Shelf</option>
      </select>
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">+ Add New Book</button>
      </div>
  </div>

</form>
</div>

<script>
  $(document).ready(function() {
    $('#sectionId').change(function() {
      var sectionId = $(this).val();

      $.ajax({
        url: `http://127.0.0.1:3000/api/shelfs?section_id=${sectionId}`, 
        method: 'GET',
        dataType: 'json',
        success: function(response) {
          var shelves = response;
          var shelfSelect = $('#shelfId');

          shelfSelect.empty();

          $.each(shelves, function(index, shelf) {
            shelfSelect.append($('<option></option>').val(shelf.id).text(shelf.name));
          });
        },
        error: function(xhr, status, error) {
          console.log(error);
        }
      });
    });
  });
</script>

app/views/books/show.html.erb
<div class="panel-group" style="width: 50vw; margin: auto">
    <h2>Book Information</h2>
    <% if flash[:notice].present? %>
      <div style="color: red" class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="panel panel-info">
      <div class="panel-heading">Book Name</div>
      <div class="panel-body"><%= @book.name %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Author</div>
      <div class="panel-body"><%= @book.author %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Publicatino Year</div>
      <div class="panel-body"><%= @book.publication_year %></div>
    </div>
    <% if can? :manage, Book %>
    <br /><br />
    <form method="POST" action="<%= book_path(id: @book.id)  %>">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <input name="_method" value="DELETE" type="hidden">
        <div class="input-group-btn">
        <button class="btn btn-danger" type="submit">Delete Book</button>
        </div>
    </form>
    <div style="margin: 2vh 0vw">
    <button class="btn btn-warning" onclick="location.href='<%= edit_book_path(@book) %>'">Edit Book</button>
    <div>
    <% end%>

</div>

app/views/members/edit.html.erb
<div style="width: 40vw;">
<h1>Edit Member</h1>
<form class="form-horizontal" method="POST" action="<%= member_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >
  <input name="_method" value="PUT"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label"> First Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[firstName]" value="<%= @member.firstName%>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Last Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[lastName]" value="<%= @member.lastName%>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Address</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[address]" value="<%= @member.address%>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Mobile Number</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[mobileNumber]" value="<%= @member.mobileNumber%>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Expiry Date</label>
    <div class="col-sm-10">
      <input type="date" class="form-control" name="member[expiryDate]" value="<%= @member.expiryDate%>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Role</label>
    <div class="col-sm-10">
      <select class="form-control" name="member[role]">
       <option>Select Role</option>
       <option value="admin" <%= 'selected' if @member.role == "admin" %>>Admin</option>
       <option value="user" <%= 'selected' if @member.role == "user" %>>User</option>
      </select>
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Update Member</button>
      </div>
  </div>
</form>
</div>

app/views/members/index.html.erb
<div>
<h1>Library Members</h1>
<form class="form-horizontal" method="GET" action="http://127.0.0.1:3000/api/members">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >
    <div class="form-group" style="width: 40vw">
        <div class="col-sm-10">
        <input placeholder="Enter Email" class="form-control" name="email"/>
        </div>
        <button type="submit" class="btn btn-primary">Seach Member</button>
    </div>
</form>
<ol class="list-group">
  <% if @members.empty? %>
    <p>No Members. Please add the member.</p>
  <% end %>
  <% @members.each do |member| %>
    <li class="list-group-item list-group-item-success"><%= link_to "#{member.email.to_s}", member_path(member) %></li>
  <% end %>
</ol>
</div>

app/views/members/new.html.erb
<div style="width: 40vw;">
<h1>Add New Member</h1>
<form class="form-horizontal" method="POST" action="<%= members_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label"> First Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[firstName]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Last Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[lastName]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Address</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[address]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Mobile Number</label>
    <div class="col-sm-10">
      <input class="form-control" name="member[mobileNumber]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Expiry Date</label>
    <div class="col-sm-10">
      <input type="date" class="form-control" name="member[expiryDate]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label"> Role</label>
    <div class="col-sm-10">
      <select class="form-control" name="member[role]">
       <option>Select Role</option>
       <option value="admin">Admin</option>
       <option value="user">User</option>
      </select>
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">+ Add New Member</button>
      </div>
  </div>
</form>
</div>

app/views/members/search.html.erb
<div style="margin: 2vh 5vw">
<h2>Search Result</h2>
<% if @members.any? %>
<ol class="list-group">
  <% @members.each do |member| %>
      <li class="list-group-item list-group-item-success"><%= link_to member.firstName + " " + member.lastName, member_path(member) %></li>
  <% end %>
</ol>
<% else %>
  <p>No matching members found.</p>
<% end %>

app/views/members/show.html.erb
<div class="panel-group" style="width: 50vw; margin: auto">
    <h2>Member Information</h2>
    <div class="panel panel-info">
      <div class="panel-heading">First Name</div>
      <div class="panel-body"><%= @member.firstName %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Last Name</div>
      <div class="panel-body"><%= @member.lastName %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Address</div>
      <div class="panel-body"><%= @member.address %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Mobile Number</div>
      <div class="panel-body"><%= @member.mobileNumber %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Expiry Date And Status</div>
      <div class="panel-body">
      <% if @member.expiryDate.present? && @member.expiryDate < Date.today %>
        <p style="color: red"><%= @member.expiryDate.to_s + " (Invalid)" %></p>
      <% else %>
        <p style="color: green"><%= @member.expiryDate.to_s + " (Valid)" %></p>
      <% end %>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Role</div>
      <div class="panel-body"><%= @member.role %></div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">Email</div>
      <div class="panel-body"><%= @member.email %></div>
    </div>
    <% if can? :manage, Member%>
    <br /><br />
    <div style="width: 150px;">
    <button class="btn btn-warning" onclick="location.href='<%= edit_member_path(@member) %>'">Edit Member</button>
    <br /><br />
    <button class="btn btn-warning" onclick="location.href='<%= edit_member_registration_path %>'">Update Password</button>
    <div>
    <% end%>

</div>

app/views/sections/edit.html.erb
<div style="width: 40vw;">
<h1>Edit Section</h1>
<form class="form-horizontal" method="POST" action="<%= section_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >
  <input name="_method" value="PUT"  type="hidden" >
  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="section[name]" value="<%= @section.name %>"/>
    </div>
  </div>
  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Update Section</button>
      </div>
  </div>

</form>
</div>

app/views/sections/index.html.erb
<div>
<h1>Sections</h1>
<ol class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item list-group-item-success"><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ol>
<% if can? :manage, Section%>
 <%= link_to "+ Add New Section", new_section_path(), class: 'btn btn-primary btn-lg' %>
<% end %>
</div>

app/views/sections/new.html.erb
<div style="width: 40vw;">
<h1>Add New Section</h1>
<form class="form-horizontal" method="POST" action="<%= sections_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="section[name]"/>
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">+ Add New Section</button>
      </div>
  </div>
</form>
</div>

app/views/sections/show.html.erb
<h1><%= @section.name + " Section" %></h1>
<h3><%= "Shelfs In This Section" %></h3>
<ol class="list-group">
<% Shelf.all.each do |shelf|%>
<%if @section.id == shelf.section_id%>
    <li class="list-group-item list-group-item-success"><%=link_to shelf.name, shelf_path(shelf) %></li>
<%end%>
<%end%>
</ol>
<% if can? :manage, Section%>
    <%= link_to "+ Add New Shelf", new_shelf_path(), class: 'btn btn-primary btn-lg' %>
    <br /><br />
    <%= link_to "Edit Section Name", edit_section_path(), class: 'btn btn-warning btn-lg' %>

    <br /><br />
    <form method="POST" action="<%= section_path(id: @section.id)  %>">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <input name="_method" value="DELETE" type="hidden">
        <div class="input-group-btn">
            <button class="btn btn-danger" type="submit">Delete Section</button>
        </div>
    </form>
<%end%>

app/views/shelfs/edit.html.erb
<div style="width: 40vw;">
<h1>Edit Shelf</h1>
<form class="form-horizontal" method="POST" action="<%= shelf_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >
  <input name="_method" value="PUT"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label">Shelf Name</label>
    <div class="col-sm-10">
     <input class="form-control" name="shelf[name]" value="<%= @shelf.name %>"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Section</label> 
    <div class="col-sm-10">
      <select class="form-control" name="shelf[section_id]">
      <option>Select Section</option>
      <% Section.all.each do |section| %>
        <option value="<%= section.id %>" <%= 'selected' if @shelf.section_id == section.id %>><%= section.name %></option>
      <% end %>
    </select>
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Update Shelf</button>
      </div>
  </div>

</form>
</div>

app/views/shelfs/index.html.erb
<div>
<% if flash[:notice].present? %>
  <div style="color: red" class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<h1>Shelfs</h1>
<% if @shelfs.empty? %>
  <p>No shelfs. Please add the shelfs.</p>
<% end %>
<ol class="list-group">
  <% @shelfs.each do |shelf| %>
    <li class="list-group-item list-group-item-success"><%= link_to shelf.name, shelf_path(shelf) %></li>
  <% end %>
</ol>
<% if can? :manage, Shelf%>
 <%= link_to "+ Add New Shelf", new_shelf_path(), class: 'btn btn-primary btn-lg' %>
<% end %>
</div>

app/views/shelfs/new.html.erb
<div style="width: 40vw;">
<h1>Add New Shelf</h1>
<form class="form-horizontal" method="POST" action="<%= shelfs_path  %>">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >

  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="shelf[name]"/>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Section</label> 
    <div class="col-sm-10">
      <select class="form-control" name="shelf[section_id]">
      <option >Select Section</option>
          <% Section.all.each do |section| %>
            <option value="<%= section.id %>"><%= section.name %></option>
          <% end %>
      </select> 
    </div>
  </div>

  <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">+ Add New Shelf</button>
      </div>
  </div>

</form>
</div>

app/views/shelfs/show.html.erb
<h1><%= @shelf.name + " Shelf" %></h1>
<h3><%= "Books In This Section" %></h3>
<ol class="list-group">
<% Book.all.each do |book|%>
<%if @shelf.id == book.shelf_id%>
    <li class="list-group-item list-group-item-success"><%=link_to book.name, book_path(book) %></li>
<%end%>
<%end%>
</ol>

<% if can? :manage, Shelf%>
    <%= link_to "+ Add New Book", new_book_path(), class: 'btn btn-primary btn-lg' %>
    <br /><br />
    <%= link_to "Edit Shelf", edit_shelf_path(), class: 'btn btn-warning btn-lg' %>
    <br /><br />
    <form method="POST" action="<%= shelf_path(id: @shelf.id)  %>">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <input name="_method" value="DELETE" type="hidden">
        <div class="input-group-btn">
            <button class="btn btn-danger" type="submit">Delete Shelf</button>
            </div>
    </form>
<%end%>