config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  root 'sections#index'
  
  get 'sessions/new'

  namespace :api do
    get 'members/index'
  end

  namespace :api do
    get 'books/index'
  end
  
   resources :sections
   resources :shelfs
   resources :books
   resources :members

   namespace :api do
      resources :shelfs, only: [:index]
      resources :books, only: [:index]
      resources :members, only: [:index]
   end


   
   
end

app/models/Permission.rb
class Permission < Struct.new(:member)

    def allow
        member && member.role == "admin" 
    end    
end    

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(member)
     member ||= Member.new 
      if member.role == "admin" 
        can :manage, Section
        can :manage, Shelf
        can :manage, Book
        can :manage, Member
      else
        can :read, Section
        can :read, Shelf
        can :read, Book
        can :read, Member
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :shelf
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :shelf, dependent: :destroy
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :section
  has_many :book, dependent: :destroy
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  def index
    name = params[:name]
    @books = Book.where("name LIKE ?", "%#{name}%")
    @books
  end
end

app/controllers/api/shelfs_controller.rb
class Api::ShelfsController < ApplicationController
  def index
    section_id = params[:section_id]
    render json: Shelf.where(section_id: section_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_member!
 load_and_authorize_resource

 def current_user
    current_member
 end  
 rescue_from CanCan::AccessDenied do |exception|
   redirect_to request.referrer, :alert => exception.message
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    Book.create!(book_params)
    redirect_to books_path, notice: 'Book Created Successfully'             
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def search
    @books = Book.includes(:shelf => :section).where('name LIKE ?', "%#{params[:name]}%")
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :publication_year, :shelf_id)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
  @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to root_url, notice: 'Member was successfully created.'
    else
      redirect_to root_url, notice: 'Unable to create member.'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to member_path(@member), notice: 'Member was successfully updated.'
    else
      redirect_to members_path, notice: 'Unable to update member'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to root_url, notice: ' Member was successfully destroyed And Logged Out.'

  end

  def search
    @members = Member.where('firstName LIKE ?', "%#{params[:name]}%")
  end

  private

  def member_params
    params.require(:member).permit(:firstName, :lastName, :mobileNumber, :address, :expiryDate, :role)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to section_path(@section), notice: 'Section was successfully created.'
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])

    if @section.update(section_params)
      redirect_to section_path(@section), notice: 'Section was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    redirect_to sections_path, notice: @section.name + ' Section was successfully destroyed.'
  end

  private

  def section_params
    params.require(:section).permit(:name)
  end
end

app/controllers/shelfs_controller.rb
class ShelfsController < ApplicationController
  def index
    @shelfs = Shelf.all
  end

  def show
    @shelf = Shelf.find(params[:id])
  end

  def new
    @shelf = Shelf.new
  end

  def create
    @shelf = Shelf.new(shelf_params)
    @section_id = params[:section_id]

    if @shelf.save
      redirect_to shelf_path(@shelf), notice: 'Shelf was successfully created.'
    else
      render :new
    end
  end

  def edit
    @shelf = Shelf.find(params[:id])
  end

  def update
    @shelf = Shelf.find(params[:id])

    if @shelf.update(shelf_params)
      redirect_to shelf_path(@shelf), notice: 'Shelf was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @shelf = Shelf.find(params[:id])
    @shelf.destroy

    redirect_to shelfs_path, notice: @shelf.name + ' Shelf was successfully destroyed.'
  end

  private

  def shelf_params
    params.require(:shelf).permit(:name, :section_id)
  end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/api/members_helper.rb
module Api::MembersHelper
end

app/helpers/api/shelf_helper.rb
module Api::ShelfHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_loginAndSignup.html.erb
<% if member_signed_in? %>
    <li> <%= link_to "Logged In As #{current_member.email}", member_path(current_member), class: 'nav-link' %> </li>
    <li style="margin: 10px 0px"><form method="POST" action="<%= destroy_member_session_path  %>">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <input name="_method" value="DELETE" type="hidden">
        <div class="input-group-btn">
        <button class="btn btn-danger" type="submit">Logg Out</button>
        </div>
    </form></li>
<% else %>
    <li> <%= link_to 'Sign Up', new_member_registration_path, class: 'nav-link'  %> </li>
    <li> <%= link_to 'Login', new_member_session_path, class: 'nav-link'  %> </li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid" style="display:flex; justify-content:space-between;">
    <div class="navbar-header">
      <p class="navbar-brand">BOOKS APP</p>
    </div>
    <ul class="nav navbar-nav">
    <% if member_signed_in? %>
      <% if can? :manage, Member%>
       <li> <%= link_to 'Library Members', members_path, class: 'nav-link' %> </li>
      <% end%>
      <li> <%= link_to 'Sections', sections_path, class: 'nav-link' %> </li>
      <li> <%= link_to 'Shelfs', shelfs_path, class: 'nav-link' %> </li>
      <li> <%= link_to 'Books', books_path, class: 'nav-link' %></li>
      <li> <%= render 'layouts/search' %></li>
    <% end%>  
      <li> <%= render 'layouts/loginAndSignup' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_search.html.erb
<div style="margin: 1vh 0vw 0vh 0vw">
<form class="form-horizontal" method="GET" action="http://127.0.0.1:3000/api/books">
  <input name="authenticity_token" value="<%= form_authenticity_token%>"  type="hidden" >
    <div class="form-group" style="width: 40vw">
        <div class="col-sm-10">
        <input placeholder="Enter Book Name To Search Its Location" class="form-control" name="name"/>
        </div>
        <button type="submit" class="btn btn-primary">Seach Book</button>
    </div>
</form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKS APP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div style="margin: 2vh 5vw">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <%= yield %>
    <div>
  </body>
</html>